# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XJFAIIkyStIgfKV0cI7FH3g3Bvv0y5c
"""

!pip install rouge
!pip install transformers

from google.colab import files

uploaded = files.upload()

import os
import re
from pathlib import Path
import pandas as pd

albums = []
songs = []
lyrics = []

# Assuming ORIGINAL_ALBUMS is a list of album names you want to filter by
# For example, if you want to include all albums in the excel, you might not need this filter
# Or you would define it based on your data.
ORIGINAL_ALBUMS = ["Fearless", "Red", "1989", "Reputation", "Lover", "Folklore", "Evermore", "Midnights"] # Example, adjust as needed

# The 'uploaded' variable contains a dictionary where keys are filenames and values are file contents.
# We need to extract the filename from the uploaded dictionary to read the excel file.
if uploaded:
    # Assuming only one file was uploaded and it's the Excel file
    file_name = list(uploaded.keys())[0]
    file_content = uploaded[file_name]

    # Read the Excel file into a pandas DataFrame
    df_excel = pd.read_excel(file_content)

    # Iterate through the DataFrame to extract information, assuming specific column names
    # Adjust 'Album', 'Song', 'Lyrics' to match your Excel column names
    for index, row in df_excel.iterrows():
        album_name = row['Album'] # Assuming 'Album' is a column in your excel
        song_name = row['Song Name'] # Assuming 'Song' is a column in your excel
        raw_lyrics = str(row['Lyrics']) # Assuming 'Lyrics' is a column in your excel

        if album_name in ORIGINAL_ALBUMS:
            albums.append(album_name)
            songs.append(song_name)

            # Clean up the lyrics by replacing non-standard characters
            raw_lyrics = raw_lyrics.encode('ascii', 'replace').decode().replace('?', ' ')
            raw_lyrics = re.sub('(?!)\s+', ' ', raw_lyrics)
            # Corrected escape sequence

            # Remove lyrics header
            raw_lyrics = re.sub('.*Lyrics', '', raw_lyrics)

            # Remove end characters (number + 'Embed' or number + 'KEmbed')
            raw_lyrics = re.sub('[0-9]+KEmbed', '', raw_lyrics)
            raw_lyrics = re.sub('[0-9]+Embed', '', raw_lyrics)

            # Clean up section's tags
            section_pattern = re.compile(r'(?<!\n\n)\[([^\]]+)\]') # Corrected escape sequence
            raw_lyrics = section_pattern.sub(r'\n[\1]', section_pattern.sub(r'\n[\1]', raw_lyrics))

            # Remove firsts empty lines
            empty_lines = re.compile(r'^\s*') # Corrected escape sequence
            raw_lyrics = empty_lines.sub('', raw_lyrics)

            lyrics.append(raw_lyrics)

df = pd.DataFrame({'Album': albums, 'Song': songs, 'Lyrics': lyrics})

display(df.head(3))

"""# **Playlist Generation**

## BERT Sentiment Analysis
"""

#from BERT
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('google-bert/bert-base-uncased',
                                          clean_up_tokenization_spaces=True)
print(tokenizer)
tokenized = tokenizer(["I am", "trying to find my place"], padding='longest', return_tensors="pt")
print(tokenized)

import torch
from torch import nn
from transformers import BertModel
pretrained_model = BertModel.from_pretrained("google-bert/bert-base-uncased")
print(pretrained_model)

def get_bert_embedding(text, model, tokenizer, device):
    """Get BERT [CLS] embedding for a single text."""
    model.eval()
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=512)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        # Extract [CLS] token embedding (first token)
        embedding = outputs.last_hidden_state[:, 0, :].squeeze()

    return embedding.cpu()

def compute_similarity(embedding1, embedding2):
    """Compute cosine similarity between two embeddings."""
    from torch.nn.functional import cosine_similarity
    return cosine_similarity(embedding1.unsqueeze(0), embedding2.unsqueeze(0)).item()

# Setup for embedding exploration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
pretrained_model.to(device)
print(f"Using: {device}")

reference_text = "Welcome to New York"
print(f"Choose a song: {reference_text}")

reference_embedding = get_bert_embedding(reference_text, pretrained_model, tokenizer, device)
import heapq
most_similarity = -1
most_review = ""
similar_songs = []
display(df.head(5))

top_songs = 13
print(len(df))
for i in range(len(df)):

    rev_embedding = get_bert_embedding(df['Lyrics'][i], pretrained_model, tokenizer, device)
    sim = compute_similarity(rev_embedding, reference_embedding) #instead of inital prompt its users prompt
    #heapq.heappush(similar_songs, (sim, df['Song'][i]))
    item = (sim, df['Song'][i])
    #print(len(similar_songs))
    if (len(similar_songs) < top_songs):
      heapq.heappush(similar_songs, item)
    else:
      if (sim > similar_songs[0][0]):
        heapq.heappop(similar_songs)
        heapq.heappush(similar_songs, item)

    if (sim > most_similarity):
      most_similarity = sim
      most_review = df['Lyrics'][i]

       # heapq.heappush(similar_songs, smallest)
#simular_songs = sorted(similar_songs, reverse=True) #now its sorted where top is most similar
#add all songs to heap, reverse order based on score, and then take top 13
print("Most similar")
print(most_similarity)
print(most_review)
#print(similar_songs)
for song in similar_songs:
  print(song)

"""## Generative AI"""

!pip install -q -U google-generativeai
import google.generativeai as genai
from google.colab import userdata

# Retrieve and configure the API key
genai.configure(api_key=userdata.get('GOOGLE_API_KEY'))

model = genai.GenerativeModel('models/gemini-2.5-flash')
#Prompt 1
system_instruction_for_lyrics = (
    "Write a song in the style of Taylor Swift for the given title. "
    "Do not include any spoken dialogue or stage directions."
)

user_query_for_lyrics = "Let's Go (Battle)"

# Combine the system instruction and user query into a single, comprehensive prompt
full_prompt = f"{system_instruction_for_lyrics}\n\n{user_query_for_lyrics}"

print(f"Prompt:\n{full_prompt}")

# 4. Generate content using the full prompt, generation config, and safety settings
response = model.generate_content(full_prompt)
#response = model.generate_content("Write a song in the style of Taylor Swift with the title 'Let's Go (Battle)'")
print(response.text)

reference_embedding = get_bert_embedding(response.text, pretrained_model, tokenizer, device)
import heapq
most_similarity = -1
most_review = ""
similar_songs2 = []
top_songs = 13
print(len(df))
for i in range(len(df)):
    rev_embedding = get_bert_embedding(df['Lyrics'][i], pretrained_model, tokenizer, device)
    sim = compute_similarity(rev_embedding, reference_embedding) #instead of inital prompt its users prompt
    #heapq.heappush(similar_songs, (sim, df['Song'][i]))
    item = (sim, df['Song'][i])
    #print(len(similar_songs))
    if (len(similar_songs2) < top_songs):
      heapq.heappush(similar_songs2, item)
    else:
      if (sim > similar_songs2[0][0]):
        heapq.heappop(similar_songs2)
        heapq.heappush(similar_songs2, item)

    if (sim > most_similarity):
      most_similarity = sim
      most_review = df['Lyrics'][i]
print("Most similar")
print(most_similarity)
print(most_review)
#print(similar_songs)
for song in similar_songs2:
  print(song)

model = genai.GenerativeModel('models/gemini-2.5-flash')
##This is prompt 2
# Incorporate System Instructions directly into the Prompt
# For text-only models like 'gemini-pro', system instructions are best handled by prepending them to your user query.
system_instruction_for_lyrics = (
    "Write a song in the style of Taylor Swift for the given title. "
    "Do not include any spoken dialogue or stage directions."
    "Use emotional and poetic language as if writing a diary entry."
)

#user_query_for_lyrics = "Let's Go (Battle)"

# Combine the system instruction and user query into a single, comprehensive prompt
full_prompt = f"{system_instruction_for_lyrics}\n\n{user_query_for_lyrics}"

print(f"Prompt:\n{full_prompt}")
# 4. Generate content using the full prompt, generation config, and safety settings
response = model.generate_content(full_prompt)
#response = model.generate_content("Write a song in the style of Taylor Swift with the title 'Let's Go (Battle)'")
print(response.text)

#take 2

reference_embedding = get_bert_embedding(response.text, pretrained_model, tokenizer, device)
import heapq
most_similarity = -1
most_review = ""
similar_songs3 = []
top_songs = 13
#print(len(df))
for i in range(len(df)):
    rev_embedding = get_bert_embedding(df['Lyrics'][i], pretrained_model, tokenizer, device)
    sim = compute_similarity(rev_embedding, reference_embedding) #instead of inital prompt its users prompt
    #heapq.heappush(similar_songs, (sim, df['Song'][i]))
    item = (sim, df['Song'][i])
    #print(len(similar_songs))
    if (len(similar_songs3) < top_songs):
      heapq.heappush(similar_songs3, item)
    else:
      if (sim > similar_songs3[0][0]):
        heapq.heappop(similar_songs3)
        heapq.heappush(similar_songs3, item)

    if (sim > most_similarity):
      most_similarity = sim
      most_review = df['Lyrics'][i]
print("Most similar")
print(most_similarity)
print(most_review)
#print(similar_songs)
for song in similar_songs3:
  print(song)

model = genai.GenerativeModel('models/gemini-2.5-flash')
from google.generativeai.types import GenerationConfig
##This is prompt 3 (with temperature low)
system_instruction_for_lyrics = (
    "Write a song in the style of Taylor Swift for the given title. "
    "Do not include any spoken dialogue or stage directions."
    "You are a pop artist with a background in country music."
)

#user_query_for_lyrics = "Let's Go (Battle)"

# Combine the system instruction and user query into a single, comprehensive prompt
full_prompt = f"{system_instruction_for_lyrics}\n\n{user_query_for_lyrics}"

print(f"Prompt:\n{full_prompt}")

generation_config = GenerationConfig(temperature=0.5)

# 4. Generate content using the full prompt, generation config, and safety settings
response = model.generate_content(full_prompt, generation_config=generation_config)
#response = model.generate_content("Write a song in the style of Taylor Swift with the title 'Let's Go (Battle)'")
print(response.text)

model = genai.GenerativeModel('models/gemini-2.5-flash')
##This is prompt 3 (high temperature)
# Incorporate System Instructions directly into the Prompt
# For text-only models like 'gemini-pro', system instructions are best handled by prepending them to your user query.
system_instruction_for_lyrics = (
    "Write a song in the style of Taylor Swift for the given title. "
    "Do not include any spoken dialogue or stage directions."
    "You are a pop artist with a background in country music."
)

#user_query_for_lyrics = "Let's Go (Battle)"

# Combine the system instruction and user query into a single, comprehensive prompt
full_prompt = f"{system_instruction_for_lyrics}\n\n{user_query_for_lyrics}"

print(f"Prompt:\n{full_prompt}")

# Create a GenerationConfig object
generation_config = GenerationConfig(temperature=3)

# 4. Generate content using the full prompt, generation config, and safety settings
response = model.generate_content(full_prompt, generation_config=generation_config)
#response = model.generate_content("Write a song in the style of Taylor Swift with the title 'Let's Go (Battle)'")
print(response.text)

#take 3

reference_embedding = get_bert_embedding(response.text, pretrained_model, tokenizer, device)
import heapq
most_similarity = -1
most_review = ""
similar_songs4 = []
top_songs = 13
#print(len(df))
for i in range(len(df)):
    rev_embedding = get_bert_embedding(df['Lyrics'][i], pretrained_model, tokenizer, device)
    sim = compute_similarity(rev_embedding, reference_embedding) #instead of inital prompt its users prompt
    #heapq.heappush(similar_songs, (sim, df['Song'][i]))
    item = (sim, df['Song'][i])
    #print(len(similar_songs))
    if (len(similar_songs4) < top_songs):
      heapq.heappush(similar_songs4, item)
    else:
      if (sim > similar_songs4[0][0]):
        heapq.heappop(similar_songs4)
        heapq.heappush(similar_songs4, item)

    if (sim > most_similarity):
      most_similarity = sim
      most_review = df['Lyrics'][i]
print("Most similar")
print(most_similarity)
print(most_review)
#print(similar_songs)
for song in similar_songs4:
  print(song)

"""**Few shot learning: examples of other song titles and lyrics**"""

model = genai.GenerativeModel('models/gemini-2.5-flash')
#few shot learning
system_instruction_for_lyrics = (
    "Write a song with the given title. "
    """Example: Paper Rings
    Output:
[Verse 1]
The moon is high
Like your friends were the night that we first met
Went home and tried to stalk you on the internet
Now I've read all of the books beside your bed
The wine is cold
Like the shoulder that I gave you in the street
Cat and mouse for a month or two or three
Now I wake up in the night and watch you breathe

[Pre-Chorus]
(Ayy)
Kiss me once 'cause you know I had a long night (Oh)
Kiss me twice 'cause it's gonna be alright (Uh)
Three times 'cause I waited my whole life (One, two, one, two, three, four)

[Chorus]
I like shiny things, but I'd marry you with paper rings
Uh-huh, that's right
Darling, you're the one I want, and
I hate accidents, except when we went from friends to this
Uh-huh, that's right
Darling, you're the one I want
In paper rings, in picture frames, in dirty dreams
Oh, you're the one I want

[Verse 2]
In the winter, in the icy outdoor pool
When you jumped in first, I went in too
I'm with you even if it makes me blue
Which takes me back
To the color that we painted your brother's wall
Honey, without all the exes, fights and flaws
We wouldn't be standing here so tall, so

[Pre-Chorus]
(Ayy)
Kiss you once 'cause I know you had a long night (Oh)
Kiss you twice 'cause it's gonna be alright (Uh)
Three times 'cause you waited your whole life (One, two, one, two, three, four)
Ah

[Chorus]
I like shiny things, but I'd marry you with paper rings
Uh-huh, that's right
Darling, you're the one I want, and
I hate accidents, except when we went from friends to this
Uh-huh, that's right
Darling, you're the one I want
In paper rings, in picture frames, in dirty dreams
Oh, you're the one I want


[Bridge]
I want to drive away with you
I want your complications too
I want your dreary Mondays
Wrap your arms around me, baby boy
I want to drive away with you
I want your complications too
I want your dreary Mondays
Wrap your arms around me, baby boy
Uh-huh

[Chorus]
I like shiny things, but I'd marry you with paper rings
Ah-ah, that's right, you're the one I want
I hate accidents, except when we went from friends to this
Ah-ah, darling, you're the one I want
I like shiny things, but I'd marry you with paper rings
Uh-huh, that's right
Darling, you're the one I want, and
I hate accidents, except when we went from friends to this
Uh-huh, that's right
Darling, you're the one I want
In paper rings, in picture frames, in all my dreams
You're the one I want
In paper rings, in picture frames, in all my dreams
Oh, you're the one I want


[Outro]
You're the one I want, one I want
You're the one I want, one I want"""
"""Example: Prompt: my tears ricochet
Output:
[Verse 1]
We gather here, we line up, weepin' in a sunlit room
And if I'm on fire, you'll be made of ashes, too
Even on my worst day, did I deserve, babe
All the hell you gave me?
'Cause I loved you, I swear I loved you
'Til my dying day

[Chorus]
I didn't have it in myself to go with grace
And you're the hero flying around, saving face
And if I'm dead to you, why are you at the wake?
Cursing my name, wishing I stayed
Look at how my tears ricochet

[Verse 2]
We gather stones, never knowing what they'll mean
Some to throw, some to make a diamond ring
You know I didn't want to have to haunt you
But what a ghostly scene
You wear the same jewels that I gave you
As you bury me

[Chorus]
I didn't have it in myself to go with grace
'Cause when I'd fight, you used to tell me I was brave
And if I'm dead to you, why are you at the wake?
Cursing my name, wishing I stayed
Look at how my tears ricochet

[Bridge]
And I can go anywhere I want
Anywhere I want, just not home
And you can aim for my heart, go for blood
But you would still miss me in your bones
And I still talk to you (When I'm screaming at the sky)
And when you can't sleep at night (You hear my stolen lullabies)

[Chorus]
I didn't have it in myself to go with grace
And so the battleships will sink beneath the waves
You had to kill me, but it killed you just the same
Cursing my name, wishing I stayed
You turned into your worst fears
And you're tossing out blame, drunk on this pain
Crossing out the good years
And you're cursing my name, wishing I stayed
Look at how my tears ricochet
"""
)

user_query_for_lyrics = "Let's Go (Battle)"

# Combine the system instruction and user query into a single, comprehensive prompt
full_prompt = f"{system_instruction_for_lyrics}\n\n{user_query_for_lyrics}"

#print(f"Prompt:\n{full_prompt}")

# 4. Generate content using the full prompt, generation config, and safety settings
response = model.generate_content(full_prompt)
#response = model.generate_content("Write a song in the style of Taylor Swift with the title 'Let's Go (Battle)'")
print(response.text)

#take 4

reference_embedding = get_bert_embedding(response.text, pretrained_model, tokenizer, device)
import heapq
most_similarity = -1
most_review = ""
similar_songs5 = []
top_songs = 13
#print(len(df))
for i in range(len(df)):
    rev_embedding = get_bert_embedding(df['Lyrics'][i], pretrained_model, tokenizer, device)
    sim = compute_similarity(rev_embedding, reference_embedding) #instead of inital prompt its users prompt
    #heapq.heappush(similar_songs, (sim, df['Song'][i]))
    item = (sim, df['Song'][i])
    #print(len(similar_songs))
    if (len(similar_songs5) < top_songs):
      heapq.heappush(similar_songs5, item)
    else:
      if (sim > similar_songs5[0][0]):
        heapq.heappop(similar_songs5)
        heapq.heappush(similar_songs5, item)

    if (sim > most_similarity):
      most_similarity = sim
      most_review = df['Lyrics'][i]
print("Most similar")
print(most_similarity)
print(most_review)
#print(similar_songs)
for song in similar_songs5:
  print(song)

"""# Choosing a Playlist"""

top_score = 0.0
optionA = []
if (similar_songs2[0][0] > similar_songs3[0][0]) & (similar_songs2[0][0] > similar_songs4[0][0]) & (similar_songs2[0][0] > similar_songs5[0][0]):
  top_score = similar_songs2[0][0]
  optionA = similar_songs2
elif(similar_songs3[0][0] > similar_songs4[0][0]) & (similar_songs3[0][0]> similar_songs5[0][0]) & (similar_songs3[0][0] > similar_songs2[0][0]):
  top_score = similar_songs3[0][0]
  optionA = similar_songs3
elif(similar_songs4[0][0] > similar_songs5[0][0]) & (similar_songs4[0][0] > similar_songs3[0][0]) & (similar_songs4[0][0] > similar_songs2[0][0]):
  top_score = similar_songs4[0][0]
  optionA = similar_songs4
else:
  optionA = similar_songs5
  top_score = similar_songs5[0][0]

#also save the best playlist to print at the end with album cover

prompt_chosen = ""
playlist = []
if (similar_songs[0][0] > optionA[0][0]):
  prompt_chosen = reference_text
  playlist = similar_songs
else:
  prompt_chosen = user_query_for_lyrics
  playlist = optionA
print(prompt_chosen)
for song in playlist:
  print(song)

"""#Image Generation"""

!pip install -U diffusers

pip install -U diffusers transformers accelerate

"""## CLIP Embeddings"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("greg115/album-covers-images")

print("Path to dataset files:", path)

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

# The Kaggle dataset was downloaded to this path by `kagglehub.dataset_download`
# This path should contain the extracted dataset files.
KAGGLE_DATASET_ROOT = Path("/kaggle/input/album-covers-images")

# We will use KAGGLE_DATASET_ROOT as our primary data directory.
DATASET_DIR = KAGGLE_DATASET_ROOT

class AlbumCoverDataset(Dataset):
    """
    Dataset of album cover images.
    Returns raw PIL images, which will be processed by CLIPProcessor.
    """

    def __init__(self, data_dir):
        self.data_dir = Path(data_dir)
        # Recursively look for image files (JPG, JPEG, PNG) in the data_dir and its subdirectories
        self.image_files = sorted(list(self.data_dir.rglob("*.jpg"))) + \
                           sorted(list(self.data_dir.rglob("*.jpeg"))) + \
                           sorted(list(self.data_dir.rglob("*.png")))

        if len(self.image_files) == 0:
            raise ValueError(f"No image files (JPG/JPEG/PNG) found in {data_dir} or its subdirectories.")

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        img = Image.open(self.image_files[idx]).convert('RGB')
        return img # Return raw PIL Image

# Check if the directory exists before attempting to load
if not DATASET_DIR.exists():
    raise FileNotFoundError(f"Dataset directory not found: {DATASET_DIR}. Please ensure the Kaggle dataset is downloaded and extracted.")

# Custom collate_fn to handle PIL Images directly in the DataLoader
def collate_fn_pil(batch):
    return batch

dataset = AlbumCoverDataset(data_dir=DATASET_DIR)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True, collate_fn=collate_fn_pil) # Increased batch size for efficiency

print(f"Dataset loaded: {len(dataset)} images")
print(f"Batch size: {dataloader.batch_size}")
print(f"Total batches: {len(dataloader)}")

# Displaying a sample image directly from PIL, as the dataloader now yields PIL images
if len(dataset) > 0:
    sample_pil_image = dataset[0]
    plt.imshow(sample_pil_image)
    plt.title("Sample Album Cover (PIL Image)")
    plt.axis('off')
    plt.show()

# PRECOMPUTE DENSE EMBEDDINGS USING CLIP
# This computes dense embeddings of all of the album cover images using CLIP
# You should review this code -- observe how CLIP has a processor for
# preparing the inputs, as well as a get_image_features method for
# retrieving the embeddings. The results resulting image_embeddings have a
# row for every image and uses an embedding dimension of 512

import torch
from transformers import CLIPProcessor, CLIPModel
from PIL import Image # Import PIL Image
from tqdm.auto import tqdm # For progress bar

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32", weights_only=False).to(device)
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

all_embeddings_list = []

# Iterate through the dataloader, which now yields batches of PIL images
with torch.no_grad():
    for batch_idx, batch_pil_images in tqdm(enumerate(dataloader), total=len(dataloader), desc="Computing CLIP embeddings"):
        # batch_pil_images is a list of PIL Images (due to DataLoader batching)
        # Process the batch of PIL images using the CLIP processor
        inputs = clip_processor(images=batch_pil_images, return_tensors="pt", padding=True, truncation=True).to(device)

        # Get image features from the model
        # The get_image_features method seems to return a BaseModelOutputWithPooling object here.
        # We need to access the 'pooler_output' attribute to get the actual tensor.
        outputs = clip_model.get_image_features(**inputs)
        batch_embeddings = outputs.pooler_output

        # Normalize the embeddings
        batch_embeddings = batch_embeddings / batch_embeddings.norm(dim=-1, keepdim=True)

        all_embeddings_list.append(batch_embeddings.cpu()) # Move to CPU to prevent GPU memory overflow during concatenation

# Concatenate all batch embeddings into a single tensor
image_embeddings = torch.cat(all_embeddings_list, dim=0)

print(f"Pre-computed embeddings: {image_embeddings.shape}")

def find_most_similar_image(text_query, image_embeddings, images, model, processor, device):
    """
    Find the image most similar to a text query using CLIP.

    Args:
        text_query: Text description (string)
        image_embeddings: Pre-computed CLIP image embeddings (N, 512)
        images: List of N PIL Images
        model: CLIP model
        processor: CLIP processor
        device: torch device

    Returns:
        most_similar_image: The PIL Image most similar to the query
        similarity_score: The similarity score (float)
    """
    processed = processor(text=[text_query], return_tensors="pt", padding=True).to(device)
    encode = model.get_text_features(**processed).pooler_output # Access the actual tensor here
    encode = encode / encode.norm(dim=-1, keepdim=True)
    # Move image_embeddings to the same device as 'encode' before matrix multiplication
    sim = torch.matmul(encode, image_embeddings.to(device).T)
    most = torch.argmax(sim, dim=1).item()
    return images[most], sim[0, most]



# Encode the text query using CLIP's text encoder
# Normalize the text embedding (divide by its L2 norm)
# Compute similarities between text embedding and all pre-computed image embeddings
# Find the index of the highest similarity
# Return the corresponding image and similarity score
# Test using the provided test_similarity_search() function below

def test_similarity_search(test_queries):
    """Run test queries and visualize results."""
    results = []
    for query in test_queries:
        result_image, score = find_most_similar_image(
            query, image_embeddings, dataset,
            clip_model, clip_processor, device
        )
        results.append((query, result_image, score))

    fig, axes = plt.subplots(len(test_queries), 2, figsize=(8, 3*len(test_queries)))
    for i, (query, img, score) in enumerate(results):
        axes[i, 0].text(0.5, 0.5, f'"{query}"', ha='center', va='center', fontsize=11, wrap=True)
        axes[i, 0].axis('off')
        axes[i, 1].imshow(img)
        axes[i, 1].set_title(f'Similarity: {score:.3f}', fontsize=12)
        axes[i, 1].axis('off')
    plt.suptitle("CLIP Text-to-Image Search Results", fontsize=14, y=0.995)
    plt.tight_layout()
    plt.show()


# Run tests
queries = ["Let's Go (Battle)", "Welcome to New York", "The Great Divide", prompt_chosen]
test_similarity_search(queries)

"""## Stable Diffusion"""

import torch
from diffusers import DiffusionPipeline
#import matplotlib.pyplot as plt

# Load a pre-trained stable diffusion model
# You might need to authenticate with Hugging Face if you encounter issues with model download
# For example, by running `!huggingface-cli login` in a new cell and providing your token.
pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipe.to("cuda")

# Generate images at different guidance scales
#prompt = f'an album cover for a Taylor Swift album titled {prompt_chosen}'
prompt = f'an album cover for a Taylor Swift album titled "Speak Now"'
#prompt = "an album cover for a Taylor Swift album titled " + prompt_chosen

fig, axes = plt.subplots(1, 4, figsize=(16, 4))

for idx, guidance_scale in enumerate([0, 3, 7, 12]):
    image = pipe(prompt, guidance_scale=guidance_scale).images[0]
    axes[idx].imshow(image)
    axes[idx].set_title(f'Guidance Scale = {guidance_scale}')
    axes[idx].axis('off')

plt.suptitle(f'"{prompt}"', fontsize=14)
plt.tight_layout()
plt.show()

# Commented out IPython magic to ensure Python compatibility.
import os
import zipfile
#change to new zipfile after everything else works
# Install gdown (to be able to download files from Google Drive)
!pip install gdown

# Download dataset
os.makedirs('input', exist_ok=True)
path_to_dataset = "input/dataset.zip"

if not os.path.exists(path_to_dataset):
    !gdown 1ZRPvcJB47s5pmy5eXmgXf0LXn1-8YqiY -O input/dataset.zip
else:
    print(f"Already downloaded `{path_to_dataset}`")

# Unzip dataset into 'input' folder
with zipfile.ZipFile(path_to_dataset, 'r') as zip_ref:
    zip_ref.extractall('input/dataset')

# Remove zip file
os.remove(path_to_dataset)

# List input directory
# %ls input/

print('Done')

"""### Conditioning"""

import torch
from diffusers import AutoPipelineForImage2Image
from diffusers.utils import make_image_grid, load_image

pipeline = AutoPipelineForImage2Image.from_pretrained(
    "stable-diffusion-v1-5/stable-diffusion-v1-5", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipeline.enable_model_cpu_offload()
# remove following line if xFormers is not installed or you have PyTorch 2.0 or higher installed
#pipeline.enable_xformers_memory_efficient_attention()

# prepare image
#url = "https://drive.google.com/file/d/1c3KrwS89Nt9kA6e5eTzmBccVefDPJqB6/view?usp=sharing"
init_image = load_image("/content/speak-now.jpeg")

prompt = "An album cover for a Taylor Swift album titled Enchanted"

# pass prompt and image to pipeline
image = pipeline(prompt, image=init_image).images[0]
make_image_grid([init_image, image], rows=1, cols=2)

pipeline = AutoPipelineForImage2Image.from_pretrained(
    "stable-diffusion-v1-5/stable-diffusion-v1-5", torch_dtype=torch.float16, variant="fp16", use_safetensors=True, guidance_scale=5
)
pipeline.enable_model_cpu_offload()
# remove following line if xFormers is not installed or you have PyTorch 2.0 or higher installed
#pipeline.enable_xformers_memory_efficient_attention()

# prepare image
#url = "https://drive.google.com/file/d/1c3KrwS89Nt9kA6e5eTzmBccVefDPJqB6/view?usp=sharing"
init_image = load_image("/content/speak-now.jpeg")

prompt = "A blue album cover titled Enhanted with a fairytale style of art"

# pass prompt and image to pipeline
image = pipeline(prompt, image=init_image).images[0]
make_image_grid([init_image, image], rows=1, cols=2)