# -*- coding: utf-8 -*-
"""IP_Adapter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIRBfNOu6aSZy5X_4nCR7V-X3FRMDAGM

**IP Adapter:**
Used https://huggingface.co/docs/diffusers/using-diffusers/ip_adapter
"""

import torch
from diffusers import AutoPipelineForText2Image
from diffusers.utils import load_image

pipeline = AutoPipelineForText2Image.from_pretrained(
  "stabilityai/stable-diffusion-xl-base-1.0",
  torch_dtype=torch.float16
).to("cuda")
pipeline.load_ip_adapter(
  "h94/IP-Adapter",
  subfolder="sdxl_models",
  weight_name="ip-adapter_sdxl.bin"
)
pipeline.set_ip_adapter_scale(0.8)

#image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/ip_adapter_diner.png")
#style_image = load_image("/content/AlbumCovers/img7.jpeg")
image = load_image("/content/red.jpeg")
#image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/ip_adapter_diner.png")
pipeline(
    prompt="Taylor Swift standing by a Lighthouse",
    ip_adapter_image=image,
    negative_prompt="deformed, ugly, wrong proportion, low res, bad anatomy, worst quality, low quality",
).images[0]

#import torch
from diffusers import DDIMScheduler
from transformers import CLIPVisionModelWithProjection
#from diffusers.utils import load_image

image_encoder = CLIPVisionModelWithProjection.from_pretrained(
    "h94/IP-Adapter",
    subfolder="models/image_encoder",
    torch_dtype=torch.float16,
)

pipeline = AutoPipelineForText2Image.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    image_encoder=image_encoder,
)
pipeline.scheduler = DDIMScheduler.from_config(pipeline.scheduler.config)
pipeline.load_ip_adapter(
  "h94/IP-Adapter",
  subfolder="sdxl_models",
  weight_name=["ip-adapter-plus_sdxl_vit-h.safetensors", "ip-adapter-plus-face_sdxl_vit-h.safetensors"]
)
pipeline.set_ip_adapter_scale([0.7, 0.3])
# enable_model_cpu_offload to reduce memory usage
pipeline.enable_model_cpu_offload()

face_image = load_image("/content/tay.jpg")
style_folder = "/content/AlbumCovers"
style_images = [load_image(f"{style_folder}/img{i}.jpeg") for i in range(11)]

generator = torch.Generator(device="cpu").manual_seed(0)

pipeline(
    prompt="an album titled Lighthouse",
    ip_adapter_image=[style_images, face_image],
    negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality",
).images[0]